Issue #2392: Product Generation Framework:
+ Set up the Product Generation Framework to pass Python EventSet objects
to Product Generators.

+ Need to discuss whether we want to pass in dialogInputInfo as well. I suspect
the answer is 'yes' and this is not hard to implement, but I want to make sure.

+ WARNING: I removed this code block from Legacy_ProductGenerator.py:

hazardEvent.setEndTime(datetime.datetime.fromtimestamp(sys.maxsize))
hazardEvent.set('fallBelow', sys.maxsize*1000)

datetime.datetime.fromtimestamp(sys.maxsize) does not work on a 64 bit machine. It only works on 32-bit machines. It produces the following error:

ValueError: timestamp out of range for platform time_t